### ISSUE TITLE
ubertooth-btle master branch write-to-file segfault

### ISSUE THREAD

**Issue by Crypt0s** [greatscottgadgets/ubertooth#147] opened 2016-02-02 17:01 UTC
All file-write options in ubertooth-btle (in the master branch) fail with a segfault:

>  ubertooth-btle -p -r /tmp/file
> Segmentation fault (core dumped)

> ubertooth-btle -p -q /tmp/pie
> Segmentation fault (core dumped)

**Comment by elli89** [comment] 2016-02-02 17:53
I see! This issue is caused by my latest patches. I will fix this.

**Comment by dominicgs** [comment] 2016-02-02 18:22
Fixed in b28d9fc by @elli89

**Closed by dominicgs** 2016-02-02 18:22 UTC
